apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: helloworld.lernkube.io
spec:
  group: lernkube.io
  names:
    kind: HelloWorld
    plural: helloworlds
    singular: helloworld
    shortNames:
      - hw
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        # schema used for validation
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                email:
                  type: string
                message:
                  type: string
---
# Deploy CRD 
apiVersion: lernkube.io/v1
kind: HelloWorld
metadata:
  name: helloworld-crd-test
spec:
  email: helloworld@gmail.com
  message: HelloWorld