# Custom Resource Definition - CRD 
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: myresources.lernkube.io
spec:
  group: lernkube.io
  names:
    kind: MyResource
    plural: myresources
    singular: myresource
    shortNames:
      - mr
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        # schema used for validation
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                message:
                  type: string
                reason:
                  type: string
---
# Creating an Object using CRD
apiVersion: lernkube.io/v1
kind: MyResource
metadata:
  name: test-myresource
spec:
  message: "hello world"
  reason: "learning crds"